### ISSUE TITLE
[이슈] requrements에 PyQt5 없음

### ISSUE THREAD

**Issue by cha2hyun** [binchoo/selnium-kakao-vaccine-reservation#16]
## 재현 절차
pipenv install
pipenv shell
python qtmain.py

## 이슈 내용
Traceback (most recent call last):
  File "qtmain.py", line 7, in <module>
    from PyQt5.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PyQt5'

**Comment by binchoo** [comment]
@cha2hyun 이슈 등록 감사합니다.
`requirements.txt` 파일에 의존 패키지 `pyqt5`를 반영하겠습니다.

**Comment by binchoo** [comment]
```bash
pip install -r requirements.txt
python qtmain.py
```

변경된 `requirements.txt`로 패키지 설치 수행한 뒤, GUI 노출 확인하였습니다.
master로 머지합니다.
