### ISSUE TITLE
[이슈] GUI 중지시 팅김 현상

### ISSUE THREAD

**Issue by cha2hyun** [binchoo/selnium-kakao-vaccine-reservation#17]
## 재현 절차
1. 로그인
2. 브라우저설정
3. 알럿 클릭
4. 시간 설정
5. 시작
6. 중지

## 이슈 내용
Traceback (most recent call last):
  File "qtmain.py", line 138, in stop_reservation_macro
    reservation.interrupt()
NameError: name 'reservation' is not defined

## 기대 결과
중지되지 않고 팅김

**Comment by binchoo** [comment]
@cha2hyun 
https://github.com/binchoo/selenium-kakao-vaccine-reservation/blob/e2a77c2833d4971d03b058a520aaa424cc7740a7/qtmain.py#L101-L113

해당 현상은 reservation이 전역 컨텍스트로 등록되지 않아 발생하는 널 포인터 엑셥션입니다. 이 이슈 참조하여 수정하도록 하겠습니다. 감사합니다.

**Comment by binchoo** [comment]
@cha2hyun 

정지버튼 클릭 시 널 포인터 엑셉션으로 프로그램 자체가 닫히는 이슈 해결하였습니다. master로 머지하였습니다.

이 변경이 실제 예약 절차에 부수 효과를 낳았을 수도 있기 때문에, 충분한 테스트가 더 필요합니다.

![GIF 2021-08-05 오후 3-46-57](https://user-images.githubusercontent.com/15683098/128304961-a00402bb-e4ba-4721-9db2-aac912460b25.gif)
