### ISSUE TITLE
[이슈] 지역 설정 시 CTRL+C 하였을 때 TypeError: init() missing 1 required positional argument: 'region'

### ISSUE THREAD

**Issue by leegajsdoifb** [binchoo/selnium-kakao-vaccine-reservation#30]
## 질문 요약
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    reservation(login(), region_selection())
  File "main.py", line 82, in reservation
    vaccine_reservation = LegacyVaccineReservation(login_cookie)
TypeError: __init__() missing 1 required positional argument: 'region'
컨트롤+c 이후에 이런 오류가 뜹니다ㅠ

**Comment by binchoo** [comment]
@leegajsdoifb 이슈 등록 감사합니다. 

현재 GUI 개발에 집중하던 터라 (`qtmain.py`)
커맨드 라인 인터페이스 (`main.py`)쪽 코드는 수정이 거의 없었네요.
수정 반영 완료되면 다시 코멘트 드리겠습니다.

**Comment by binchoo** [comment]
@leegajsdoifb 해당 이슈는
`main.py`의 82번째 줄에서 `LegacyVaccinReservation` 객체를 생성할 때, `region` 값을 두 번째 인자로 넘겨주지 않아 발생하였습니다.
10시 10분 이후 수정 배포 후 클로즈 합니다.
https://github.com/binchoo/selenium-kakao-vaccine-reservation/blob/035ae1b1d6eea16b93b36c1c3fd2065873ddb1db/main.py#L82

**Comment by binchoo** [comment]
https://github.com/binchoo/selenium-kakao-vaccine-reservation/releases/tag/1.09
에 반영하였습니다. 확인 부탁드립니다 👍🏻

**Comment by leegajsdoifb** [comment]
감사합니다!
근데 제가 이쪽 분야를 잘 몰라서 GUI 실행법을 모르는데
cmd 들어가서
cd 경로 입력하고
GUI 코드 입력했는데 창같은게 실행이 안되더라구요ㅠ

**Comment by binchoo** [comment]
@leegajsdoifb 일단 말씀하신 과정에 잘못된 부분은 없어 보입니다!

- `qtmain.py`가 보이는 경로에서 이렇게 실행하셨으면 잘 될 것입니다.
```bash
pip install -r requirements.txt (최초 한 번)
python qtmain.py
```

- 안 된다면, 파이썬 버전이 3.7 이상의 것인지 알아보아야 겠습니다.
  CMD 창에서 `python --version` 을 입력했을 때, `3.7.*` 형태로 나오는 지 확인 부탁드립니다.

- 파이썬이 3.7 이상이 맞다면, 사용하시는 컴퓨터 환경을 알려주시면 큰 도움이 될 것 같습니다.

- 일반적으로 `.exe` 실행 파일이 익숙하실 것이므로, 실행 파일을 제공할 수 있도록 방안을 연구해 보겠습니다. 감사합니다.

**Comment by leegajsdoifb** [comment]
C:\Users\Desktop\selenium-kakao-vaccine-reservation-master\selenium-kakao-vaccine-reservation-master>python qtmain.py
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
이렇게 뜹니다...!

**Comment by leegajsdoifb** [comment]
Python 3.8.2
window10 입니다!

**Comment by binchoo** [comment]
@leegajsdoifb 정보 감사합니다.
1. CMD에서 `where python` 입력합니다.
2. `C:\Users\name\AppData\Local\Microsoft\WindowsApps\python.exe` 처럼 나올텐데, **파이썬 설치된 경로**를 잘 기억하시면 됩니다.
3. 아래 내용대로 진행해 보시면 어떨까 합니다.
![image](https://user-images.githubusercontent.com/15683098/128361637-4271882b-7300-4396-897b-0799e33e83ab.png)

출처 - https://doongkibangki.tistory.com/24
