### ISSUE TITLE
[개선] Reservation 요청 구조 개선 제안

### ISSUE THREAD

**Issue by cha2hyun** [binchoo/selnium-kakao-vaccine-reservation#32]
## 제안 내용

before : 무한루프(find_vaccine_remaining -> 검증 -> try_reservation -> 검증) : 리퀘스트 2회
tobe : find_vaccine_remaining -> 검증 -> 무한루프(try_reservation -> 검증) : 리퀘스트 1회

1. 프로그램 실행 후 루프가 도는동안 지도의 좌표는 변하질 않는다.
2. 따라서 좌표안의 병원 데이터 또한 변하질 않는다. (organization_code)
3. 추후 사용자가 백신타입을 지정하게 된다면 vaccine_type도 변하질 않는다.
4. find_vaccine_remaining에서 지속하여 리퀘스트를 보내거나 검증하지 않아도, try_reservation에서 어차피 status값 확인으로 걸러진다.
5. 따라서 find_vaccine_remaining은 최초 1회만 실행 되어도 된다.

**Comment by binchoo** [comment]
@cha2hyun 안녕하세요. 구조 제안 감사합니다.

현재 2번에 적어주신 내용과 실제 구현이 다른 부분이 있어서 짚어드립니다.

`find_vaccine_remaining` 호출마다 병원들의 'status' 값이 바뀔 수 있습니다.
`status := INPUT_YET | AVAILABLE | EXHUASTED | CLOSED` 가 있는 것으로 알고 있으며

`find_vaccine_remaining`은 `status`가 `AVAILABLE`인 병원을 병원을 하나 반환합니다.
반환되는 객체의 예시는 아래와 같습니다. 
```
{
  'orgCode': '12358681', 
  'orgName': '곽내과의원', 
  'address': '서울 종로구 자하문로 58', 
  'x': 126.97120895207867, 'y': 37.581253855387715, 
  'status': 'AVAILABLE', 
  'leftCounts': 11
}
```
이 객체에서 `orgCode`를 획득하고 현재 구현상 모든 백신 타입에 4가지에 대해 `try_reservation`을 2번씩 보내게 됩니다.

## 브루트 포스 요청에 대한 부담

- `find_vaccine_remaining`을 1회만 호출하는  알고리즘은. 좌표 영역에 존재하는 모든 병원들의 `orgCode`를 사용하여 `try_reservation`을 보내는 모양새가 될 것입니다.
- `find_vaccine_remaining`는 카카오 맵에서 주기적으로 콜하는 API이기 때문에 무수히 서버에 요청되어도 차단 위험이 적다고 예상합니다.
- `try_reservation`은 백신 API이므로 브루트 포스 요청이 들어오면 필터링 될 소지가 있다고 생각합니다.

## 다른 개선 방향

`constant.py` > `url`> `kakao`> `check_organization_format` 라는, 
현재 안 쓰이는 API가 하나 있는데요. orgCode를 실어서 보내면, 해당 기관이 취급하는 백신 및 잔여량에 대한 정보를 내려줍니다. 하지만 이 API도 브루트 포스 콜을 하기에는 망설여지는 상태입니다.
```
[{
    "vaccineType": "Pfizer",
    "vaccineName": "화이자",
    "vaccineCode": "VEN00013",
    "status": "INPUT_YET",
    "leftCount": 0
}, {
    "vaccineType": "Moderna",
    "vaccineName": "모더나",
    "vaccineCode": "VEN00014",
    "status": "INPUT_YET",
    "leftCount": 0
}], "selectableVaccineCodes": ["VEN00013", "VEN00014"]
}
```

대신 이 정보를 활용하면, 지금 백신 예약 2회 시도하는 부분을 스마트하게 바꿀 수 있겠군요. 
따라서 차후 개선 방향은 try_loops=2 를 없애고 위 API를 사용하는 게 어떨지요?

---
### 개선점 요약
AS-IS
- find_vaccine_remaining에서 `AVAILABLE` 상태인 기관 중 첫번째 값만을 반환한다. 
- try_reservation에서 설정된 백신 타입에 대해 2회씩 예약을 시도하는 것은 리퀘스트를 최대 8번 낭비한다.

TO-BE
- find_vaccine_remaining의 시그니쳐를 find_available_organizations로 변경한다.
- find_available_organizations은 `AVAILABLE` 상태인 기관들의 리스트를 반환한다.
- try_reservation은 `orgCode`의 리스트를 전달 받도록 시그니쳐를 변경한다.
- try_reservation은 check_organization_format API를 사용, 유저가 원하는 백신 타입을 취급하는 기관에게만 리퀘스트를 보낸다. 따라서 리퀘스트 낭비를 방지한다.

**Comment by binchoo** [comment]
`find_vaccine_remaining`을 1회만 호출하는  알고리즘은
좌표 영역에 존재하는 모든 병원들의 `orgCode`를 사용하여 `try_reservation`을 보내는 모양새가 될 것입니다.

`find_vaccine_remaining`는 지도 API이기 때문에 요청이 무수히 서버에 전달되어도 차단 위험이 전혀 없다고 예상합니다만
`try_reservation`은 백신 API이므로 브루트 포스 요청이 들어오면 필터링 될 소지가 있다고 생각합니다.

**Comment by binchoo** [comment]
`constant.py` > `url`> `kakao`> `check_organization_format` 라는, 

현재 안 쓰이는 API가 하나 있는데요. orgCode를 실어서 보내면, 해당 기관이 취급하는 백신 및 잔여량에 대한 정보를 내려줍니다. 하지만 이 API도 브루트 포스 콜을 하기에는 망설여지는 상태입니다.
```
[{
    "vaccineType": "Pfizer",
    "vaccineName": "화이자",
    "vaccineCode": "VEN00013",
    "status": "INPUT_YET",
    "leftCount": 0
}, {
    "vaccineType": "Moderna",
    "vaccineName": "모더나",
    "vaccineCode": "VEN00014",
    "status": "INPUT_YET",
    "leftCount": 0
}], "selectableVaccineCodes": ["VEN00013", "VEN00014"]
}
```

**Comment by cha2hyun** [comment]
필터링에 대한 내용을 간과했네요,
말씀처럼 필터링 걸릴 수도 있을것 같아요 😅
+) 자세한 피드백 감사합니다
+) 코드 스타일이 너무 깔끔하고 읽기 편하네요

질문) 혹시 잔여백신이 없는데 reservation url로 리퀘스트를 보내면 status 500이 나오나요?

**Comment by binchoo** [comment]
@cha2hyun 님 확인 감사합니다. 
이 이슈를 열어주셔서 차후 개선점을 몇 가지 발견하게 되었습니다.

500 응답이 내려오는 경우는 거의
- 로그인 쿠키가 유효하지 않았을 때입니다. 이 때 500응답이나 401 응답이 내려왔습니다.
- 취득한 로그인 쿠키는 반드시 1회 이상 `https://vaccine.kakao.com/api/v1/user` API를 호출하는데 쓰여야합니다. 
  - 앱에서는 일전에 사용한 로그인 쿠키를 불러올 때랑
  - 브라우저에서 새 로그인 쿠키를 취득했을 때 실행됩니다. 
  - `kakaoUserValidity` 함수입니다.
- 본인의 스크립트에서 500이 내려온다면 로그인 정보를 다시 셋팅 후 `kakaoUserValidity` 콜을 보내 보세요.
- 잔여 백신이 없을 때는 200이 아닌 것은 확실합니다만, 객체가 담겨 있긴 합니다. 한 번 확인해 보겠습니다!

**Comment by binchoo** [comment]
@cha2hyun 잔여 백신 없을 경우

403 코드 응답이지만 객체는 담겨 있습니다. 500이 내려온다면 로그인 쿠키 유효한지 확인 바랍니다.
```
{
    'code': 'NO_VACANCY',
    'desc': '잔여백신 접종 신청이\n선착순 마감되었습니다.',
    'organization': {
        'orgCode': '12358681',
        'orgName': '곽내과의원',
        'confirmId': '592212085',
        'phoneNumber': '02-735-5135',
        'address': '서울 종로구 자하문로 58',
        'x': 126.97120895207867,
        'y': 37.581253855387715,
        'openHour': {
            'date': '2021-08-06',
            'dayOfWeek': '금요일',
            'dayOff': False,
            'openHour': {
                'start': '09:00',
                'end': '16:00'
            },
            'lunch': {
                'start': '12:00',
                'end': '14:00'
            }
        },
        'disabled': False
    }
}
```

**Comment by cha2hyun** [comment]
고맙습니다 👍👍

**Comment by binchoo** [comment]
## 개선 내용
### Reservation 알고리즘 수정
1. 지도에서 `AVAILABLE` 상태의 기관들을 얻는다.
2. 이들 중, 유저가 선택한 백신 종류를 가진 기관들에 대해서만 백신 예약 신청을 보낸다.


수정된 내용 master에 머지하였습니다. 19시 이후 QA 1.09에 통합됩니다.
